// registry/svelte/menu/MenuItem.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    disabled?: boolean;
    onSelect?: () => void;
    hasSubmenu?: boolean;
    class?: string;
    children?: Snippet;
    submenu?: Snippet;
  }

  let {
    disabled = false,
    onSelect,
    hasSubmenu = false,
    class: className,
    children,
    submenu,
  }: Props = $props();

  function handleClick() {
    if (!disabled && onSelect) {
      onSelect();
    }
  }

  function handleKeyDown(e: KeyboardEvent) {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      handleClick();
    }
  }
</script>

<li
  role="menuitem"
  aria-disabled={disabled || undefined}
  tabindex={disabled ? -1 : 0}
  class={["menuItem", hasSubmenu || submenu ? "has-submenu" : "", className].filter(Boolean).join(" ")}
  onclick={handleClick}
  onkeydown={handleKeyDown}
>
  {#if children}
    {@render children()}
  {/if}
  {#if submenu}
    {@render submenu()}
  {/if}
</li>

// registry/react/menu/menu-item.tsx
import React from "react";
import styles from "../css/menu.module.css";

interface MenuItemProps {
  disabled?: boolean;
  onSelect?: () => void;
  submenu?: React.ReactNode;
  className?: string;
  children: React.ReactNode;
}

export function MenuItem({
  disabled = false,
  onSelect,
  submenu,
  className,
  children,
}: MenuItemProps) {
  const handleClick = () => {
    if (!disabled && onSelect) {
      onSelect();
    }
  };

  const handleKeyDown = (e: React.KeyboardEvent) => {
    if (e.key === "Enter" || e.key === " ") {
      e.preventDefault();
      handleClick();
    }
  };

  return (
    <li
      role="menuitem"
      aria-disabled={disabled || undefined}
      tabIndex={disabled ? -1 : 0}
      className={`${styles.menuItem} ${submenu ? styles.hasSubmenu : ""} ${className ?? ""}`}
      onClick={handleClick}
      onKeyDown={handleKeyDown}
    >
      {children}
      {submenu}
    </li>
  );
}
