// registry/react/menubar/menubar-item.tsx
import React from "react";
import styles from "../css/menubar.module.css";

interface MenuBarItemProps {
  label: string;
  className?: string;
  children?: React.ReactNode;
}

export function MenuBarItem({ label, className, children }: MenuBarItemProps) {
  return (
    <li
      role="menuitem"
      tabIndex={0}
      className={`${styles.menubarItem} ${className ?? ""}`}
    >
      {label}
      {children}
    </li>
  );
}

// registry/svelte/menubar/MenuBarItem.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    label: string;
    class?: string;
    children?: Snippet;
  }

  let { label, class: className, children }: Props = $props();
</script>

<li
  role="menuitem"
  tabindex={0}
  class={["menubarItem", className].filter(Boolean).join(" ")}
>
  {label}
  {#if children}
    {@render children()}
  {/if}
</li>
