// registry/svelte/groupbox/GroupBox.svelte
<script lang="ts">
  import type { HTMLFieldsetAttributes } from "svelte/elements";
  import type { Snippet } from "svelte";

  interface Props extends HTMLFieldsetAttributes {
    legend?: string;
    children?: Snippet;
    class?: string;
  }

  let { legend, children, class: className, ...rest }: Props = $props();
</script>

<fieldset class="groupbox {className ?? ''}" {...rest}>
  {#if legend}
    <legend class="legend">{legend}</legend>
  {/if}
  {#if children}
    {@render children()}
  {/if}
</fieldset>

<style>
fieldset{border:1px solid #cdd7db;border-radius:3px;box-shadow:inset 0 0 0 1px #fff;margin:0;padding:8px 10px 10px}fieldset legend{font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif}.group,fieldset{display:flex;flex-direction:column;gap:6px}.group+.group{margin-top:6px}
</style>

// registry/vue/groupbox/GroupBox.vue
<script setup lang="ts">
interface Props {
  legend?: string;
  class?: string;
}

const { legend, class: className } = defineProps<Props>();
</script>

<template>
  <fieldset :class="['groupbox', className]">
    <legend v-if="legend" class="legend">{{ legend }}</legend>
    <slot />
  </fieldset>
</template>

<style scoped>
fieldset{border:1px solid #cdd7db;border-radius:3px;box-shadow:inset 0 0 0 1px #fff;margin:0;padding:8px 10px 10px}fieldset legend{font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif}.group,fieldset{display:flex;flex-direction:column;gap:6px}.group+.group{margin-top:6px}
</style>
