// registry/svelte/listbox/ListBox.svelte
<!-- registry/svelte/listbox/ListBox.svelte -->
<script lang="ts">
  interface ListBoxItem {
    value: string;
    label: string;
    disabled?: boolean;
  }

  interface Props {
    items: ListBoxItem[];
    selectionMode?: "single" | "multiple";
    selectedValues?: string[];
    onSelectionChange?: (values: string[]) => void;
    hasShadow?: boolean;
    hasHover?: boolean;
    class?: string;
  }

  let {
    items,
    selectionMode = "single",
    selectedValues = $bindable<string[]>([]),
    onSelectionChange,
    hasShadow = false,
    hasHover = false,
    class: className,
  }: Props = $props();

  let focusedIndex = $state(-1);

  function toggleSelection(value: string) {
    let next: string[];
    if (selectionMode === "multiple") {
      next = selectedValues.includes(value)
        ? selectedValues.filter((v) => v !== value)
        : [...selectedValues, value];
    } else {
      next = [value];
    }
    selectedValues = next;
    onSelectionChange?.(next);
  }

  function handleKeyDown(e: KeyboardEvent) {
    switch (e.key) {
      case "ArrowDown":
        e.preventDefault();
        focusedIndex = focusedIndex < items.length - 1 ? focusedIndex + 1 : focusedIndex;
        break;
      case "ArrowUp":
        e.preventDefault();
        focusedIndex = focusedIndex > 0 ? focusedIndex - 1 : focusedIndex;
        break;
      case "Enter":
      case " ":
        e.preventDefault();
        if (focusedIndex >= 0 && focusedIndex < items.length) {
          toggleSelection(items[focusedIndex].value);
        }
        break;
      case "Home":
        e.preventDefault();
        focusedIndex = 0;
        break;
      case "End":
        e.preventDefault();
        focusedIndex = items.length - 1;
        break;
    }
  }
</script>

<ul
  role="listbox"
  aria-multiselectable={selectionMode === "multiple"}
  class="win7-listbox {hasShadow ? 'has-shadow' : ''} {hasHover ? 'has-hover' : ''} {className ?? ''}"
  tabindex="0"
  onkeydown={handleKeyDown}
>
  {#each items as item, index (item.value)}
    <li
      role="option"
      aria-selected={selectedValues.includes(item.value)}
      aria-disabled={item.disabled}
      class="win7-listbox-option"
      class:selected={selectedValues.includes(item.value)}
      onclick={() => !item.disabled && toggleSelection(item.value)}
    >
      {item.label}
    </li>
  {/each}
</ul>

<style>
/* registry/css/listbox.css */
/* 7.css 원본 기반 — [role=listbox] / select[multiple] 스타일 */

.win7-listbox {
  background: #fff;
  border: 1px solid #c0c1cd;
  display: block;
  font: 9pt "Segoe UI", SegoeUI, "Noto Sans", sans-serif;
  overflow-y: scroll;
  box-sizing: border-box;
}

.win7-listbox.has-shadow {
  box-shadow: 4px 4px 3px -2px #999;
}

.win7-listbox:focus {
  outline: none;
}

.win7-listbox-option {
  padding: 2px;
  cursor: default;
}

.win7-listbox.has-hover .win7-listbox-option:hover {
  background-color: #2a90ff;
  color: #fff;
}

.win7-listbox-option:focus,
.win7-listbox-option[aria-selected="true"] {
  background-color: #2a90ff;
  color: #fff;
}

.win7-listbox-option.selected {
  background-color: #2a90ff;
  color: #fff;
}
</style>

// registry/react/listbox/listbox.tsx
// registry/react/listbox/listbox.tsx
import React, { useState, useCallback, useRef } from "react";
import styles from "../css/listbox.module.css";

export interface ListBoxItem {
  value: string;
  label: string;
  disabled?: boolean;
}

export interface ListBoxProps {
  /** 리스트에 표시할 항목 목록 */
  items: ListBoxItem[];
  /** 선택 모드: "single" (기본) 또는 "multiple" */
  selectionMode?: "single" | "multiple";
  /** 현재 선택된 값 목록 (controlled) */
  selectedValues?: string[];
  /** 선택 변경 시 콜백 */
  onSelectionChange?: (values: string[]) => void;
  /** 그림자 효과 표시 여부 */
  hasShadow?: boolean;
  /** hover 시 하이라이트 표시 여부 */
  hasHover?: boolean;
  /** 추가 CSS 클래스 */
  className?: string;
  /** 리스트박스 높이 */
  style?: React.CSSProperties;
}

export function ListBox({
  items,
  selectionMode = "single",
  selectedValues: controlledValues,
  onSelectionChange,
  hasShadow = false,
  hasHover = false,
  className,
  style,
}: ListBoxProps) {
  const [internalSelected, setInternalSelected] = useState<string[]>([]);
  const [focusedIndex, setFocusedIndex] = useState(-1);
  const listRef = useRef<HTMLUListElement>(null);

  const selected = controlledValues ?? internalSelected;

  const toggleSelection = useCallback(
    (value: string) => {
      let next: string[];
      if (selectionMode === "multiple") {
        next = selected.includes(value)
          ? selected.filter((v) => v !== value)
          : [...selected, value];
      } else {
        next = [value];
      }
      setInternalSelected(next);
      onSelectionChange?.(next);
    },
    [selected, selectionMode, onSelectionChange]
  );

  const handleKeyDown = useCallback(
    (e: React.KeyboardEvent) => {
      switch (e.key) {
        case "ArrowDown":
          e.preventDefault();
          setFocusedIndex((prev) =>
            prev < items.length - 1 ? prev + 1 : prev
          );
          break;
        case "ArrowUp":
          e.preventDefault();
          setFocusedIndex((prev) => (prev > 0 ? prev - 1 : prev));
          break;
        case "Enter":
        case " ":
          e.preventDefault();
          if (focusedIndex >= 0 && focusedIndex < items.length) {
            toggleSelection(items[focusedIndex].value);
          }
          break;
        case "Home":
          e.preventDefault();
          setFocusedIndex(0);
          break;
        case "End":
          e.preventDefault();
          setFocusedIndex(items.length - 1);
          break;
      }
    },
    [focusedIndex, items, toggleSelection]
  );

  const classNames = [
    styles.listbox,
    hasShadow && styles["has-shadow"],
    hasHover && styles["has-hover"],
    className,
  ]
    .filter(Boolean)
    .join(" ");

  return (
    <ul
      ref={listRef}
      role="listbox"
      aria-multiselectable={selectionMode === "multiple"}
      className={classNames}
      tabIndex={0}
      onKeyDown={handleKeyDown}
      style={style}
    >
      {items.map((item, index) => (
        <li
          key={item.value}
          role="option"
          aria-selected={selected.includes(item.value)}
          aria-disabled={item.disabled}
          className={`${styles["listbox-option"]} ${
            selected.includes(item.value) ? styles.selected : ""
          } ${focusedIndex === index ? styles.focused : ""}`.trim()}
          onClick={() => !item.disabled && toggleSelection(item.value)}
        >
          {item.label}
        </li>
      ))}
    </ul>
  );
}
