// registry/svelte/menubar/MenuBarItem.svelte
<script lang="ts">
  import type { Snippet } from "svelte";

  interface Props {
    label: string;
    class?: string;
    children?: Snippet;
  }

  let { label, class: className, children }: Props = $props();
</script>

<li
  role="menuitem"
  tabindex={0}
  class={["menubarItem", className].filter(Boolean).join(" ")}
>
  {label}
  {#if children}
    {@render children()}
  {/if}
</li>

// registry/react/menubar/menubar-item.jsx
import React from "react";
import styles from "../css/menubar.module.css";

export function MenuBarItem({ label, className, children }) {
  return (
    <li
      role="menuitem"
      tabIndex={0}
      className={`${styles.menubarItem} ${className ?? ""}`}
    >
      {label}
      {children}
    </li>
  );
}
