// registry/vue/tabs/TabPanel.vue
<script setup lang="ts">
import { computed, inject } from "vue";
import type { ComputedRef } from "vue";

interface Props {
  value: string;
}

const props = defineProps<Props>();

const ctx = inject<{
  activeValue: ComputedRef<string>;
}>("tabs")!;

const isActive = computed(() => ctx.activeValue.value === props.value);
</script>

<template>
  <div
    role="tabpanel"
    :id="`tabpanel-${value}`"
    :aria-labelledby="`tab-${value}`"
    :hidden="!isActive"
    class="tabpanel"
  >
    <slot />
  </div>
</template>

// registry/react/tabs/tab-panel.jsx
import React from "react";
import { useTabsContext } from "./tabs";
import styles from "../css/tabs.module.css";

export function TabPanel({ value, className, children, ...props }) {
  const { activeValue } = useTabsContext();
  const isActive = activeValue === value;

  return (
    <div
      role="tabpanel"
      id={`tabpanel-${value}`}
      aria-labelledby={`tab-${value}`}
      hidden={!isActive}
      className={`${styles.tabpanel} ${className ?? ""}`}
      {...props}
    >
      {children}
    </div>
  );
}

TabPanel.displayName = "TabPanel";
