// registry/svelte/tabs/Tabs.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { setContext } from "svelte";

  interface Props {
    defaultValue?: string;
    value?: string;
    onValueChange?: (value: string) => void;
    justified?: boolean;
    class?: string;
    children?: Snippet;
  }

  let {
    defaultValue = "",
    value: controlledValue,
    onValueChange,
    justified = false,
    class: className,
    children,
  }: Props = $props();

  let uncontrolledValue = $state(defaultValue);

  let activeValue = $derived(controlledValue !== undefined ? controlledValue : uncontrolledValue);

  function onSelect(val: string) {
    if (controlledValue === undefined) {
      uncontrolledValue = val;
    }
    onValueChange?.(val);
  }

  setContext("tabs", {
    get activeValue() { return activeValue; },
    onSelect,
  });
</script>

<menu role="tablist" class={["tablist", justified && "justified", className].filter(Boolean).join(" ")}>
  {@render children?.()}
</menu>

<style>
  /* inject-css.ts 가 registry/css/tabs.css 내용을 여기에 자동 주입 */
</style>

// registry/react/tabs/tabs.jsx
import React, { useState, useCallback, createContext, useContext } from "react";
import styles from "../css/tabs.module.css";

const TabsContext = createContext(null);

export function useTabsContext() {
  const context = useContext(TabsContext);
  if (!context) {
    throw new Error("Tab/TabPanel must be used within a Tabs component");
  }
  return context;
}

export function Tabs({
  defaultValue,
  value: controlledValue,
  onValueChange,
  justified = false,
  className,
  children,
}) {
  const [uncontrolledValue, setUncontrolledValue] = useState(defaultValue ?? "");

  const isControlled = controlledValue !== undefined;
  const activeValue = isControlled ? controlledValue : uncontrolledValue;

  const onSelect = useCallback(
    (val) => {
      if (!isControlled) {
        setUncontrolledValue(val);
      }
      onValueChange?.(val);
    },
    [isControlled, onValueChange]
  );

  const tabs = [];
  const panels = [];

  React.Children.forEach(children, (child) => {
    if (!React.isValidElement(child)) return;
    if (child.type.displayName === "Tab") {
      tabs.push(child);
    } else {
      panels.push(child);
    }
  });

  const tablistClass = [styles.tablist, justified ? styles.justified : "", className ?? ""]
    .filter(Boolean)
    .join(" ");

  return (
    <TabsContext.Provider value={{ activeValue, onSelect }}>
      <menu role="tablist" className={tablistClass}>
        {tabs}
      </menu>
      {panels}
    </TabsContext.Provider>
  );
}
