// registry/react/tabs/tab-panel.tsx
import React from "react";
import { useTabsContext } from "./tabs-context";
import styles from "../css/tabs.module.css";

interface TabPanelProps extends React.HTMLAttributes<HTMLDivElement> {
  value: string;
}

export function TabPanel({ value, className, children, ...props }: TabPanelProps) {
  const { activeValue } = useTabsContext();
  const isActive = activeValue === value;

  return (
    <div
      role="tabpanel"
      id={`tabpanel-${value}`}
      aria-labelledby={`tab-${value}`}
      hidden={!isActive}
      className={`${styles.tabpanel} ${className ?? ""}`}
      {...props}
    >
      {children}
    </div>
  );
}

TabPanel.displayName = "TabPanel";

// registry/vue/tabs/TabPanel.vue
<script setup lang="ts">
import { computed, inject } from "vue";
import type { ComputedRef } from "vue";

interface Props {
  value: string;
}

const props = defineProps<Props>();

const ctx = inject<{
  activeValue: ComputedRef<string>;
}>("tabs")!;

const isActive = computed(() => ctx.activeValue.value === props.value);
</script>

<template>
  <div
    role="tabpanel"
    :id="`tabpanel-${value}`"
    :aria-labelledby="`tab-${value}`"
    :hidden="!isActive"
    class="tabpanel"
  >
    <slot />
  </div>
</template>
