// registry/react/tabs/tab.tsx
import React from "react";
import { useTabsContext } from "./tabs-context";
import styles from "../css/tabs.module.css";

interface TabProps extends React.ButtonHTMLAttributes<HTMLButtonElement> {
  value: string;
}

export function Tab({ value, disabled, className, children, ...props }: TabProps) {
  const { activeValue, onSelect } = useTabsContext();
  const isSelected = activeValue === value;

  const handleClick = () => {
    if (!disabled) {
      onSelect(value);
    }
  };

  return (
    <button
      role="tab"
      aria-selected={isSelected}
      aria-controls={`tabpanel-${value}`}
      id={`tab-${value}`}
      disabled={disabled}
      className={`${styles.tab} ${className ?? ""}`}
      onClick={handleClick}
      {...props}
    >
      {children}
    </button>
  );
}

Tab.displayName = "Tab";

// registry/svelte/tabs/Tab.svelte
<script lang="ts">
  import type { Snippet } from "svelte";
  import { getContext } from "svelte";

  interface Props {
    value: string;
    disabled?: boolean;
    class?: string;
    children?: Snippet;
  }

  let { value, disabled = false, class: className, children }: Props = $props();

  const ctx = getContext<{ activeValue: string; onSelect: (v: string) => void }>("tabs");

  let isSelected = $derived(ctx.activeValue === value);

  function handleClick() {
    if (!disabled) {
      ctx.onSelect(value);
    }
  }
</script>

<button
  role="tab"
  aria-selected={isSelected}
  aria-controls={`tabpanel-${value}`}
  id={`tab-${value}`}
  {disabled}
  class={["tab", className].filter(Boolean).join(" ")}
  onclick={handleClick}
>
  {#if children}
    {@render children()}
  {/if}
</button>
