// registry/vue/textbox/TextBox.js.vue
<script setup>
const props = defineProps({
  multiline: {
    type: Boolean,
    default: false,
  },
  type: {
    type: String,
    default: "text",
  },
  class: {
    type: String,
    default: "",
  },
});
</script>

<template>
  <textarea
    v-if="multiline"
    :class="['textbox', props.class]"
    v-bind="$attrs"
  />
  <input
    v-else
    :type="type"
    :class="['textbox', props.class]"
    v-bind="$attrs"
  />
</template>

<style scoped>
input[type=email],input[type=number],input[type=password],input[type=text],input[type=url]{height:23px}input[type=email],input[type=number],input[type=password],input[type=text],input[type=url],textarea{background-color:#fff;border-color:#abadb3 #dbdfe6 #e3e9ef #e2e3ea;border-radius:2px;border-style:solid;border-width:1px;box-sizing:border-box;font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif;padding:3px 4px 5px;transition:border-color .5s}input[type=email]:hover,input[type=number]:hover,input[type=password]:hover,input[type=text]:hover,input[type=url]:hover,textarea:hover{border-color:#5794bf #b7d5ea #c7e2f1 #c5daed;transition:border-color .3s}input[type=email]:focus,input[type=number]:focus,input[type=password]:focus,input[type=text]:focus,input[type=url]:focus,textarea:focus{border-color:#3d7bad #a4c9e3 #b7d9ed #b5cfe7;outline:none}input[type=email]:disabled,input[type=number]:disabled,input[type=password]:disabled,input[type=text]:disabled,input[type=url]:disabled,textarea:disabled{background:#f0f0f0;border-color:#afafaf;box-shadow:inset 0 0 0 1px #fff}
</style>

// registry/svelte/textbox/TextBox.js.svelte
<script>
  let { multiline = false, class: className, type = "text", ...rest } = $props();
</script>

{#if multiline}
  <textarea class="textbox {className ?? ''}" {...rest}></textarea>
{:else}
  <input {type} class="textbox {className ?? ''}" {...rest} />
{/if}

<style>
input[type=email],input[type=number],input[type=password],input[type=text],input[type=url]{height:23px}input[type=email],input[type=number],input[type=password],input[type=text],input[type=url],textarea{background-color:#fff;border-color:#abadb3 #dbdfe6 #e3e9ef #e2e3ea;border-radius:2px;border-style:solid;border-width:1px;box-sizing:border-box;font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif;padding:3px 4px 5px;transition:border-color .5s}input[type=email]:hover,input[type=number]:hover,input[type=password]:hover,input[type=text]:hover,input[type=url]:hover,textarea:hover{border-color:#5794bf #b7d5ea #c7e2f1 #c5daed;transition:border-color .3s}input[type=email]:focus,input[type=number]:focus,input[type=password]:focus,input[type=text]:focus,input[type=url]:focus,textarea:focus{border-color:#3d7bad #a4c9e3 #b7d9ed #b5cfe7;outline:none}input[type=email]:disabled,input[type=number]:disabled,input[type=password]:disabled,input[type=text]:disabled,input[type=url]:disabled,textarea:disabled{background:#f0f0f0;border-color:#afafaf;box-shadow:inset 0 0 0 1px #fff}
</style>
