// registry/react/treeview/tree-item.tsx
// registry/react/treeview/tree-item.tsx
import React from "react";
import { useTreeViewContext } from "./treeview";

interface TreeItemProps {
  label: string;
  open?: boolean;
  collapsible?: boolean;
  children?: React.ReactNode;
}

export function TreeItem({
  label,
  open = false,
  collapsible,
  children,
}: TreeItemProps) {
  const { variants } = useTreeViewContext();
  const hasChildren = React.Children.count(children) > 0;
  const isCollapseButton = variants.includes("collapse-button");
  const shouldCollapse = (collapsible ?? isCollapseButton) && hasChildren;

  if (shouldCollapse) {
    return (
      <li>
        <details open={open}>
          <summary>{label}</summary>
          <ul>{children}</ul>
        </details>
      </li>
    );
  }

  if (hasChildren) {
    return (
      <li>
        {label}
        <ul>{children}</ul>
      </li>
    );
  }

  return <li>{label}</li>;
}

// registry/svelte/treeview/TreeItem.svelte
<!-- registry/svelte/treeview/TreeItem.svelte -->
<script lang="ts">
  import type { Snippet } from "svelte";
  import { getTreeViewContext } from "./TreeView.svelte";

  interface Props {
    label: string;
    open?: boolean;
    collapsible?: boolean;
    children?: Snippet;
  }

  let { label, open = false, collapsible, children }: Props = $props();

  const { variants } = getTreeViewContext();
  const hasChildren = !!children;
  const isCollapseButton = variants.includes("collapse-button");
  const shouldCollapse = (collapsible ?? isCollapseButton) && hasChildren;
</script>

{#if shouldCollapse}
  <li>
    <details {open}>
      <summary>{label}</summary>
      <ul>
        {@render children!()}
      </ul>
    </details>
  </li>
{:else if hasChildren}
  <li>
    {label}
    <ul>
      {@render children!()}
    </ul>
  </li>
{:else}
  <li>{label}</li>
{/if}
