// registry/vue/radiobutton/RadioButton.vue
<script setup lang="ts">
import { useId } from "vue";

interface Props {
  label: string;
  modelValue?: string;
  value?: string;
  disabled?: boolean;
  name?: string;
  class?: string;
  id?: string;
}

const { label, modelValue, value, disabled = false, name, class: className, id } = defineProps<Props>();
const emit = defineEmits<{
  "update:modelValue": [value: string];
}>();

const generatedId = useId();
const inputId = id ?? generatedId;
</script>

<template>
  <span :class="className">
    <input
      type="radio"
      :id="inputId"
      class="radio"
      :name="name"
      :value="value"
      :checked="modelValue === value"
      :disabled="disabled"
      @change="emit('update:modelValue', value ?? '')"
    />
    <label :for="inputId" class="label">{{ label }}</label>
  </span>
</template>

<style scoped>
input[type=radio]{appearance:none;-webkit-appearance:none;-moz-appearance:none;background:0;border:none;margin:0;opacity:0;position:fixed}input[type=radio]+label{align-items:center;display:inline-flex;font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif;margin-left:20px;position:relative}input[type=radio]+label:before{background:#f6f6f6;border:1px solid #8e8f8f;border-radius:50%;box-shadow:inset 0 0 0 1.5px #f4f4f4,inset 1px 1px 0 1.5px #aeaeae,inset -1px 0 0 1.5px #ddd,inset 3px 3px 6px #ccc;box-sizing:border-box;content:"";display:inline-block;height:14px;left:-20px;margin-right:6px;position:absolute;top:0;transition:.4s;width:14px}input[type=radio]+label:hover:before{border-color:#3c7fb1;box-shadow:inset 0 0 0 1.5px #def9fa,inset 1px 1px 0 1.5px #79c6f9,inset -1px -1px 0 1.5px #c6e9fc,inset 3px 3px 6px #b1dffd}input[type=radio]:checked+label:after{background:#7cd3eb;border:1.5px solid #27506d;border-radius:50%;box-shadow:inset -1px -1px 0 .5px #16638f,inset -1px -1px 0 1px #1985c0;box-sizing:border-box;content:"";display:block;height:8px;left:-17px;position:absolute;top:3px;width:8px}input[type=radio]:focus-visible+label{outline:1px dotted #000}input[type=radio]:disabled+label{filter:grayscale(1);opacity:.6}input[type=radio]:disabled:not(:checked)+label:before{opacity:.5}
</style>

// registry/svelte/radiobutton/RadioButton.svelte
<script lang="ts">
  import type { HTMLInputAttributes } from "svelte/elements";

  interface Props extends Omit<HTMLInputAttributes, "type"> {
    label: string;
    group?: string;
    value?: string;
    class?: string;
  }

  let { label, group = $bindable(""), value, class: className, id, ...rest }: Props = $props();

  const generatedId = crypto.randomUUID();
  const inputId = id ?? generatedId;
</script>

<span class={className ?? ""}>
  <input
    type="radio"
    id={inputId}
    class="radio"
    bind:group
    {value}
    {...rest}
  />
  <label for={inputId} class="label">{label}</label>
</span>

<style>
input[type=radio]{appearance:none;-webkit-appearance:none;-moz-appearance:none;background:0;border:none;margin:0;opacity:0;position:fixed}input[type=radio]+label{align-items:center;display:inline-flex;font:9pt Segoe UI,SegoeUI,Noto Sans,sans-serif;margin-left:20px;position:relative}input[type=radio]+label:before{background:#f6f6f6;border:1px solid #8e8f8f;border-radius:50%;box-shadow:inset 0 0 0 1.5px #f4f4f4,inset 1px 1px 0 1.5px #aeaeae,inset -1px 0 0 1.5px #ddd,inset 3px 3px 6px #ccc;box-sizing:border-box;content:"";display:inline-block;height:14px;left:-20px;margin-right:6px;position:absolute;top:0;transition:.4s;width:14px}input[type=radio]+label:hover:before{border-color:#3c7fb1;box-shadow:inset 0 0 0 1.5px #def9fa,inset 1px 1px 0 1.5px #79c6f9,inset -1px -1px 0 1.5px #c6e9fc,inset 3px 3px 6px #b1dffd}input[type=radio]:checked+label:after{background:#7cd3eb;border:1.5px solid #27506d;border-radius:50%;box-shadow:inset -1px -1px 0 .5px #16638f,inset -1px -1px 0 1px #1985c0;box-sizing:border-box;content:"";display:block;height:8px;left:-17px;position:absolute;top:3px;width:8px}input[type=radio]:focus-visible+label{outline:1px dotted #000}input[type=radio]:disabled+label{filter:grayscale(1);opacity:.6}input[type=radio]:disabled:not(:checked)+label:before{opacity:.5}
</style>
